export const BATCH_GET_REQ = "BATCH_GET_REQ";
export const BATCH_GET_RES = "BATCH_GET_RES";

export const ALL_BATCH_GET_REQ = "ALL_BATCH_GET_REQ";
export const ALL_BATCH_GET_RES = "ALL_BATCH_GET_RES";

export const ALL_STATES_LIST_REQ = "ALL_STATES_LIST_REQ";
export const ALL_STATES_LIST_RES = "ALL_STATES_LIST_RES";
