export const FACULTY_GET_REQ = "FACULTY_GET_REQ";
export const FACULTY_GET_RES = "FACULTY_GET_RES";
export const ALL_FACULTY_GET_REQ = "ALL_FACULTY_GET_REQ";
export const ALL_FACULTY_GET_RES = "ALL_FACULTY_GET_RES";
