export const GET_ORDER_REQ = "GET_ORDER_REQ";
export const GET_ORDER_RESP = "GET_ORDER_RESP";
export const UPDATE_ORDER_REQ = "UPDATE_ORDER_REQ";
export const UPDATE_ORDER_RESP = "UPDATE_ORDER_RESP";
export const CREATE_ORDER_REQ = "CREATE_ORDER_REQ";
export const CREATE_ORDER_RESP = "CREATE_ORDER_RESP";
export const DELETE_ORDER_REQ = "DELETE_ORDER_REQ";
export const DELETE_ORDER_RESP = "DELETE_ORDER_RESP";