export const applyLeaveSuccess = "Leave Applied Succesfully";
export const applyLeaveFaild = "Failed to Apply Leave";
export const updateDeleteSuccess = "Leave Delete Succesfully";
export const updateDeleteFailed = "Failed to Delete Leave";
export const internalServerError = "Internal Server Error";
export const approved = "Approved";
export const reject = "Rejected";
export const facultyUpdated = "Faculty Updated";
export const studentAdded = "Student Added Successfully";
