export const LEAVE_APPLY_REQ = "LEAVE_APPLY";
export const LEAVE_APPLY_RES = "LEAVE_GET";
export const LEAVE_GET_REQ = "LEAVE_GET_REQ";
export const LEAVE_GET_RES = "LEAVE_GET_RES";
export const LEAVE_DELETE_REQ = "LEAVE_DELETE_REQ";
export const LEAVE_DELETE_RES = "LEAVE_DELETE_RES";
export const LMS_RREPORT_GET_REQ = "LMS_REPORT_GET_REQ";
export const LMS_RREPORT_GET_RES = "LMS_REPORT_GET_RES";
